### ISSUE TITLE
Formatting the Docs

### ISSUE THREAD

**Issue by samuel-tate** [AlexsLemonade/refinebio-py#23]
Right now the docs look pretty cramped and messy.

We should investigate how to edit the formatting to make the docs easier to read.

Some Suggestions:

- add whitespace between functions and methods
- remove arguments in functions/methods

see the comments in #19 for more details

**Comment by dvenprasad** [comment]
In addition to the above, we should also add formatting so that it matches refine.bio branding. 
We have styled refine.bio docs to match this:
http://docs.refine.bio/en/latest/ 
☝️  is based on sphinx but uses a ReadTheDocs template. Here is the repo: https://github.com/AlexsLemonade/refinebio-docs
There is a CSS file which should help smooth this along. (I hope) 

Also, here is the dev style guide for refine.bio: https://github.com/AlexsLemonade/refinebio-design/blob/master/styleguide-dev.pdf
