### ISSUE TITLE
Handling throttled requests

### ISSUE THREAD

**Issue by jashapiro** [AlexsLemonade/refinebio-py#83]
When running code that queries the API in parallel, there is sometimes a printed output of:

```
{'detail': 'Request was throttled. Expected available in 1 second.'}
```
It is unclear to me how the pyrefinebio client is handling those responses; if it is simply ignoring/skipping them or retrying the API call after a delay (I couldn't find code to suggest it retries, but nor could I find where the printing was coming from.)

WIth enough concurrent responses, there will eventually be an unhandled Error 429:

```
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.refine.bio/v1/samples/GSM278319/
```

As you might expect, I can reduce the error rate by using fewer threads, but even with only 4 threads, I hit the throttle limit pretty quickly.

Some code to reproduce the error below:

```python
import pyrefinebio
from concurrent.futures import ThreadPoolExecutor


def get_sample_tags(sample: pyrefinebio.Sample) -> list[str]:
    keywords = sample.contributed_keywords
    tags = keywords.get("MetaSRA", [])
    return tags

executor = ThreadPoolExecutor()

experiment = pyrefinebio.Experiment.get("GSE11005")
experiment_tags = executor.map(get_sample_tags, experiment.samples)

tags = set()
for e in experiment_tags:
   tags.update(e)

print(tags)
```

(Note that I know this experiment accession does not have any contributed keywords, but it does have enough samples to consistently trigger the error, and that is the code I was working with...)

**Comment by davidsmejia** [comment]
Just wanted to chime in with the fact that we do ratelimit, creating a threadpool will only help you scale your requests a tiny bit no matter how many threads are available, especially if we implement throttling in pyrefinebio. This is because the rate limiting occurs when the API sees x requests initiated from the same IP address in y amount of time.

The thread pool will still help in scenarios where longer requests would block fetching of smaller requests.

That being said I do think it is in the best interest of our users to gracefully handle an error that we know in advance will occur.

**Comment by jashapiro** [comment]
The primary use case was interested in was for short bursts of multiple requests where the thread pool did seem to help reduce latency. 

But my bigger concern was whether when I get the `{'detail': 'Request was throttled. Expected available in 1 second.'}` printout that I am not silently losing a response. Happy to wait the 1 second as long as `pyrefinebio` is handling the throttling correctly.
